'''
@summary: Responses directly from the command line
@copyright: Copyright (c) 2012 Rackspace US, Inc.
'''


class CommandLineResponse(object):
    '''
    @summary: Bare bones object for any Command Line Connector response
    @ivar Command: The full original command string for this response
    @type Command: C{str}
    @ivar StandardOut: The Standard Out generated by this command
    @type StandardOut: C{list} of C{str}
    @ivar StandardError: The Standard Error generated by this command
    @type StandardError: C{list} of C{str}
    @ivar ReturnCode: The command's return code
    @type ReturnCode: C{int}
    '''
    def __init__(self):
        self.Command = ""
        self.StandardOut = []
        self.StandardError = []
        self.ReturnCode = None
        self.process_id=None
        return
