from ccengine.domain.base_domain import BaseDomain
        
class ComputeAtomPayload(BaseDomain):

    def __init__(self, payload):
        self.instance_id = payload.get('instance_id')
        self.state_description = payload.get('state_description')
        self.original_image_ref_url = payload.get('original_image_ref_url')
        self.availability_zone = payload.get('availability_zone')
        self.ramdisk_id = payload.get('ramdisk_id')
        self.instance_type_id = payload.get('instance_type_id')
        self.bandwidth = payload.get('bandwidth')
        self.deleted_at = payload.get('deleted_at')
        self.reservation_id = payload.get('reservation_id')
        self.user_id = payload.get('user_id')
        self.state = payload.get('state')
        self.old_state = payload.get('old_state')
        self.old_task_state = payload.get('old_task_state')
        self.ephemeral_gb = payload.get('ephemeral_gb')
        self.access_ip_v6 = payload.get('access_ip_v6')
        self.disk_gb = payload.get('disk_gb')
        self.access_ip_v4 = payload.get('access_ip_v4')
        self.kernel_id = payload.get('kernel_id')
        self.base_image_ref_url = payload.get('base_image_ref_url')
        self.host = payload.get('host')
        self.display_name = payload.get('display_name')
        self.image_ref_url = payload.get('image_ref_url')
        self.audit_period_beginning = payload.get('audit_period_beginning')
        self.root_gb = payload.get('root_gb')
        self.tenant_id = payload.get('tenant_id')
        self.created_at = payload.get('created_at')
        self.launched_at = payload.get('launched_at')
        self.memory_mb = payload.get('memory_mb')
        self.instance_type = payload.get('instance_type')
        self.vcpus = payload.get('vcpus')
        self.image_meta = payload.get('image_meta')
        self.architecture = payload.get('architecture')
        self.new_task_state = payload.get('new_task_state')
        self.audit_period_ending = payload.get('audit_period_ending')
        self.os_type = payload.get('os_type')